# Migrated Gateway API Configuration
# This is the "after" example showing the migrated configuration
# Compare with before-ingress.yaml to see the migration
#
# Related Documentation: Documentation/09-migration-guide.md

# Step 1: GatewayClass (equivalent to IngressClass)
# Usually created once per cluster by infrastructure team
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: nginx-gateway
spec:
  controllerName: gateway.nginx.org/nginx-gateway
---
# Step 2: Gateway (equivalent to Ingress Controller setup)
# TLS is configured here, not in HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  namespace: default
spec:
  gatewayClassName: nginx-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: app-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
---
# Step 3: HTTPRoute (equivalent to Ingress resource)
# Routing rules migrated here
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-app-route
  namespace: default
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
    - app.example.com
  rules:
    # Path /api with rewrite
    - matches:
        - path:
            type: PathPrefix
            value: /api
      filters:
        # Migrated from nginx.ingress.kubernetes.io/rewrite-target
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: api-service
          port: 80
    
    # Path /admin
    - matches:
        - path:
            type: PathPrefix
            value: /admin
      backendRefs:
        - name: admin-service
          port: 80
    
    # Default path /
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: web-service
          port: 80
---
# Step 4: RateLimitPolicy (migrated from annotation)
# Note: Policy support varies by Gateway implementation
apiVersion: gateway.networking.k8s.io/v1
kind: RateLimitPolicy
metadata:
  name: rate-limit-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: my-app-route
  default:
    requests: 100
    unit: "second"

# Migration Summary:
# 1. IngressClass → GatewayClass
# 2. Ingress TLS → Gateway TLS
# 3. Ingress rules → HTTPRoute rules
# 4. rewrite-target annotation → URLRewrite filter
# 5. rate-limit annotation → RateLimitPolicy resource
# 6. Single Ingress resource → Gateway + HTTPRoute (separation of concerns)

